BEGIN TRANSACTION;
INSERT INTO "customers" VALUES (1,'Adam Thompson');
INSERT INTO "customers" VALUES (2,'Brittany Lewis');
INSERT INTO "customers" VALUES (3,'Charles Evans');
INSERT INTO "customers" VALUES (4,'Danielle Garcia');
INSERT INTO "customers" VALUES (5,'Ethan Roberts');
INSERT INTO "orders" VALUES (1,1,'Smart TV');
INSERT INTO "orders" VALUES (2,2,'Laptop');
INSERT INTO "orders" VALUES (3,3,'Headphones');
INSERT INTO "orders" VALUES (4,4,'Smartphone');
INSERT INTO "orders" VALUES (5,5,'Tablet');
INSERT INTO "products" VALUES (1,'Smart TV');
INSERT INTO "products" VALUES (2,'Laptop');
INSERT INTO "products" VALUES (3,'Headphones');
INSERT INTO "products" VALUES (4,'Smartphone');
INSERT INTO "products" VALUES (5,'Tablet');
INSERT INTO "suppliers" VALUES (1,'TechDirect Inc.');
INSERT INTO "suppliers" VALUES (2,'GizmoCorp');
INSERT INTO "suppliers" VALUES (3,'Innovate Solutions');
INSERT INTO "suppliers" VALUES (4,'ElectroWorld');
INSERT INTO "suppliers" VALUES (5,'Future Tech');
INSERT INTO "product_suppliers" VALUES (1,1);
INSERT INTO "product_suppliers" VALUES (2,2);
INSERT INTO "product_suppliers" VALUES (3,3);
INSERT INTO "product_suppliers" VALUES (4,4);
INSERT INTO "product_suppliers" VALUES (5,5);
INSERT INTO "employees" VALUES (1,'Sarah Johnson',1,NULL);
INSERT INTO "employees" VALUES (2,'Liam Taylor',1,1);
INSERT INTO "employees" VALUES (3,'Emily Harris',2,NULL);
INSERT INTO "employees" VALUES (4,'Noah Clark',2,3);
INSERT INTO "employees" VALUES (5,'Olivia Martinez',3,NULL);
INSERT INTO "departments" VALUES (1,'Sales');
INSERT INTO "departments" VALUES (2,'HR');
INSERT INTO "departments" VALUES (3,'IT');
INSERT INTO "departments" VALUES (4,'Finance');
INSERT INTO "departments" VALUES (5,'Marketing');
INSERT INTO "authors" VALUES (1,'Isaac Asimov');
INSERT INTO "authors" VALUES (2,'Agatha Christie');
INSERT INTO "authors" VALUES (3,'Mark Twain');
INSERT INTO "authors" VALUES (4,'Jane Austen');
INSERT INTO "authors" VALUES (5,'H.G. Wells');
INSERT INTO "books" VALUES (1,'Foundation',1);
INSERT INTO "books" VALUES (2,'Murder on the Orient Express',2);
INSERT INTO "books" VALUES (3,'The Adventures of Tom Sawyer',3);
INSERT INTO "books" VALUES (4,'Pride and Prejudice',4);
INSERT INTO "books" VALUES (5,'The Time Machine',5);
INSERT INTO "categories" VALUES (1,'Electronics');
INSERT INTO "categories" VALUES (2,'Books');
INSERT INTO "categories" VALUES (3,'Home Appliances');
INSERT INTO "categories" VALUES (4,'Fashion');
INSERT INTO "categories" VALUES (5,'Toys');
INSERT INTO "products_with_category" VALUES (1,'Smart TV',1);
INSERT INTO "products_with_category" VALUES (2,'Laptop',1);
INSERT INTO "products_with_category" VALUES (3,'Headphones',1);
INSERT INTO "products_with_category" VALUES (4,'Pride and Prejudice',2);
INSERT INTO "products_with_category" VALUES (5,'The Time Machine',2);
COMMIT;
